# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RongSDK_iOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RongSDK_iOS
  # 步骤-1，添加融云 SDK
    pod 'RongCloudIM/IMLib', '~> 2.8.27'
    pod 'RongCloudIM/IMKit', '~> 2.8.27'

end
